config/routes.rb
Users::Application.routes.draw do

  get "vote/add"

  get "vote/remove"

  get "acomments/create"

  get "acomments/destroy"

  get "answers/create"

  get "answers/edit"

  get "answers/destroy"

  get "qcomments/create"

  get "qcomments/destroy"

  post "questions/mejor_respuesta"

  resources :questions do
    resources :qcomments, :answers, :acomments
  end

  get "message/show"

  get "message/destroy"

  get "follow/create"
  get "follow/destroy"
  get "follow/show"

  root :to => 'questions#index'

  devise_for :users

  ActiveAdmin.routes(self)

  resources :activities
  get "activities/show"

  resources :users

  match 'users/:id/edit' => 'devise/registrations#edit'

end

app/models/question.rb
class Question < ActiveRecord::Base
  include PublicActivity::Common
  
  belongs_to :user
  has_many :qcomments, 	:dependent => :delete_all
  has_many :answers, 	:dependent => :delete_all
  has_many :acomments, 	:dependent => :delete_all
  accepts_nested_attributes_for :answers
  attr_accessible :title, :text, :user_id, :mejor_respuesta
  

  validates_presence_of :title
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index]
  # GET /questions
  # GET /questions.json
  def index
    if current_user && current_user.superadmin?
        redirect_to admin_dashboard_path
    else
      @questions = Question.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @questions }
      end
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit

    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        @question.create_activity key: 'question.create', owner: current_user
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  def mejor_respuesta
    @question = Question.find(params[:Qid])

    @question.mejor_respuesta = params[:Aid]
    @question.save
    @answer = Answer.find(params[:Aid])
    @user = User.find(@answer.user_id)
    current_user.send_message(@user, "Mejor_Respuesta" , @question.id)
    redirect_to @question
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= simple_form_for(@question) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editar Pregunta</h1>

<div class="row">

<div class="well span8 offset2 text-center">
<%= simple_form_for @question,:html => { :class => "form-horizontal" } do |f| %>
  <%= f.error_notification %>
<div class="row">
        <div class=""></div>
        <div class="span4">
       		<div class="row">
        	<div class="span1">
        		Titulo 
        	</div>
        	<div class="span3">
    			<%= f.input_field :title, :label => 'Pregunta', :placeholder => 'Escribe tu pregunta aquí', :autofocus => true %><br><br>
        	</div>
        	</div>

        	<div class="row">
        	<div class="span1">
        		Contenido 
        	</div>
        	<div class="span3">
    			<%= f.text_area :text, :class =>"input-xxlarge", :size => '30x5', :label => 'Contenido', :placeholder => 'Más información sobre la pregunta.'%><br><br>
        	</div>
        	</div>
    		<%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="actions">
    <%= f.button :submit, "Registrar", :class => "btn btn-inverse" %>
  </div>
<% end %>

</div>
</div>
</div>
</div>

app/views/questions/index.html.erb
<h1>Lista de preguntas</h1>
<div class = "well text-center" >
<% @questions.each do |question| %>
  <h3> <%= link_to question.title, question %></h3>
  Hace <%= time_ago_in_words question.created_at %>
  por <%= link_to question.user.username, question.user %>
  <p>
  <%= link_to 'Detalles', question %> |
  <%= pluralize(question.qcomments.count, 'Comentario' , 'Comentarios' )%> |
  <%= pluralize(question.answers.count, 'Respuesta', 'Respuestas')%>
  </p>
<% end %>
</div>

app/views/questions/new.html.erb
<h1 class="text-center">Hacer Pregunta</h1>

<div class="row">

<div class="well span8 offset2 text-center">
<%= simple_form_for @question,:html => { :class => "form-horizontal" } do |f| %>
  <%= f.error_notification %>

      <div class="row">
        <div class=""></div>
        <div class="span4">
       		<div class="row">
        	<div class="span1">
        		Titulo 
        	</div>
        	<div class="span3">
    			<%= f.input_field :title, :label => 'Pregunta', :placeholder => 'Escribe tu pregunta aquí', :autofocus => true %><br><br>
        	</div>
        	</div>

        	<div class="row">
        	<div class="span1">
        		Contenido 
        	</div>
        	<div class="span3">
    			<%= f.text_area :text, :class =>"input-xxlarge", :size => '30x5', :label => 'Contenido', :placeholder => 'Más información sobre la pregunta.'%><br><br>
        	</div>
        	</div>
    		  <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="actions">
    <%= f.button :submit, "Registrar", :class => "btn btn-inverse" %>
  </div>
<% end %>

</div>
</div>
</div>
</div>

app/views/questions/show.html.erb
<div class="well row span10">

	<h1><%= @question.title %></h1>
	<p>
		<%= @question.text %>
	</p>
	  Hace <%= time_ago_in_words @question.created_at %>
	  por <%= link_to @question.user.username, @question.user %>
	<p>
	<% if current_user.id == @question.user_id %>
		<%= link_to 'Editar', edit_question_path(@question) %> |
		<%= link_to 'Eliminar', @question, :method => :delete, :confirm => "Esta seguro?" %>
	<% end %>
	</p>
	<div class = "span7 offset1">
		<h6><%= pluralize(@question.qcomments.count, 'Comentario' , 'Comentarios' )%> </h6>
		<div class="text-right">
		<% @question.qcomments.each do |qcomment| %>
			<hr size="5px" height="1px" color="silver">
			<p><small><%= link_to qcomment.user.username, qcomment.user %>:
				<%= qcomment.text %>
				<br>Hace <%= time_ago_in_words qcomment.created_at %></small> 
				<% if current_user.id == qcomment.user_id %>
					<%= link_to 'Eliminar comentario', [@question, qcomment], :method => :delete, :confirm => "Esta seguro?" %>
				<% end %>
			</p>
		<% end %>
		</div>
		<%= link_to_function "Comentar", "$('#coment').toggle()" %>
		<div id="coment" class="row text-center" style="display:none;">
			<%= simple_form_for [@question, @question.qcomments.build], :id => "form1" do |f| %>
			  <%= f.error_notification %>

			    <%= f.text_area :text, :class =>"input-xlarge", :size => '30x1'%><br>
			    <%= f.hidden_field :user_id, :value => current_user.id %>
			    <%= f.hidden_field :question_id, :value => @question.id %>
			    <%= f.button :submit, "Comentar pregunta", :class => "btn btn-inverse" %>
			<% end %>
		</div >
	</div>
	<div class = "well span9">
	<h6><%=  pluralize(@question.answers.count, 'Respuesta', 'Respuestas') %></h6>
	<% @question.answers.each do |answer| %>
		<hr size="5px" color="silver">
		<div class="row">
		<div class="span1 text-center">
			<%= link_to image_tag("/images/up.png", :border => 0, :width => '20' , :height => '20', :alt => '', :title => 'Votar'), vote_add_path(:Qid => @question.id, :Aid => answer.id) %><br>
        	<%= answer.votos %><br>
			<%= link_to image_tag("/images/down.png", :border => 0, :width => '20' , :height => '20', :alt => '', :title => 'Votar'), vote_remove_path(:Qid => @question.id, :Aid => answer.id) %><br>
        	<% if current_user.id == @question.user_id && @question.mejor_respuesta == nil %>
				<br><%= link_to image_tag("/images/check.png", :border => 0, :width => '20' , :height => '20', :alt => '', :title => 'Verificar'), questions_mejor_respuesta_path(:Qid => @question.id, :Aid => answer.id) , :method => 'post' %>
			<% elsif @question.mejor_respuesta == answer.id %>
				<br><%= image_tag("/images/check.png", :border => 0, :width => '20' , :height => '20', :alt => '', :title => 'Verificada')%>
        	<% end %>
		</div>
		<div class="span7">
			<h3><%= answer.text %></h3>
		<p>
			<br>Hace <%= time_ago_in_words answer.created_at %> por <%= link_to answer.user.username, answer.user %> 
	  		<% if current_user.id == answer.user_id %>
			<%= link_to '| Eliminar respuesta', [@question, answer], :method => :delete, :confirm => "Esta seguro?" %>
			<% end %>
		</p>
		</div>
		</div>
		<div class="span7 offset1">
		<h6><%= pluralize(answer.acomments.count, 'Comentario' , 'Comentarios' )%> </h6>
		<div class="text-right">
		<% answer.acomments.each do |acomment| %>
		<hr size="5px" color="silver">
		  	<p><%= link_to acomment.user.username, acomment.user %>:
			<%= acomment.text %>
			<br>Hace <%= time_ago_in_words acomment.created_at %> 
		  	<% if current_user.id == acomment.user_id %>
			<%= link_to 'Eliminar comentario', [@question, acomment], :method => :delete, :confirm => "Esta seguro?" %>
			</p>
			<% end %>
		<% end %>
		</div>
		</div>
		<%= link_to_function "Comentar", "$('#coment"+answer.id.to_s+"').toggle()" %>
		<div id="coment<%= answer.id.to_s %>" class="row text-center" style="display:none;">
		<%= simple_form_for [@question, @question.acomments.build] do |af| %>
		  <%= af.error_notification %>

		    <%= af.text_area :text, :class =>"xinput-large", :size => '30x1'%><br>
		    <%= af.hidden_field :user_id, :value => current_user.id %>
		    <%= af.hidden_field :answer_id, :value => answer.id %>
		    <%= af.button :submit, "Comentar respuesta", :class => "btn btn-inverse" %>
		<% end %>
		</div>

	<% end %>
		<hr size="5px" color="silver">
		<%= link_to_function "Hacer una respuesta", "$('#respuesta').toggle()" %>
		<div id="respuesta" class="row text-center" style="display:none;">
			<% if current_user.id == @question.user_id %>
				<%= "No puedes responder tu propia pregunta" %>
			<% else %>
				<%= simple_form_for [@question, @question.answers.build] do |f| %>
			  	<%= f.error_notification %>
				<%= f.text_area :text, :class => "input-xxlarge", :size => '30x5'%><br>
				<%= f.hidden_field :user_id, :value => current_user.id %>
				<%= f.hidden_field :question_id, :value => @question.id %>
				<%= f.hidden_field :votos, :value => 0 %>
				<%= f.button :submit, "Publicar respuesta", :class => "btn btn-inverse" %>
				<% end %>
			<% end %>
		</div>
	</div>
</div>
<script>
$(document).ready(function() {

 $('#coment1').hide(); //Initially form wil be hidden.
</script>