config/routes.rb
Users::Application.routes.draw do

  get "vote/add"

  get "vote/remove"

  get "acomments/create"

  get "acomments/destroy"

  get "answers/create"

  get "answers/edit"

  get "answers/destroy"

  get "qcomments/create"

  get "qcomments/destroy"

  post "questions/mejor_respuesta"

  resources :questions do
    resources :qcomments, :answers, :acomments
  end

  get "message/show"

  get "message/destroy"

  get "follow/create"
  get "follow/destroy"
  get "follow/show"

  root :to => 'questions#index'

  devise_for :users

  ActiveAdmin.routes(self)

  resources :activities
  get "activities/show"

  resources :users

  match 'users/:id/edit' => 'devise/registrations#edit'

end

app/models/user.rb
class User < ActiveRecord::Base
  include PublicActivity::Common
  
  devise :database_authenticatable, :recoverable, 
         :rememberable, :trackable, :validatable, :registerable 
  	
  attr_accessible :login, :name, :lname, :username, :email, :password, :password_confirmation, 
                  :remember_me, :avatar

  has_many :questions,  :dependent => :delete_all
  has_many :qcomments,  :dependent => :delete_all
  has_many :answers,    :dependent => :delete_all
  has_many :acomments,  :dependent => :delete_all
  has_many :votes,      :dependent => :delete_all

  validates_uniqueness_of :username
  validates_presence_of :username
  validates_presence_of :name
  validates_presence_of :lname

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/user-avatar.png"

    # Virtual attribute for authenticating by either username or email
	# This is in addition to a real persisted field like 'username'
	attr_accessor :login

  acts_as_followable

  acts_as_follower

  acts_as_messageable

	# app/models/user.rb

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

	### This is the correct method you override with the code above
	### def self.find_for_database_authentication(warden_conditions)
	### end 

  extend FriendlyId
  friendly_id :username
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :except => [:new, :index]
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def find
    @user = User.new
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @title = @user.username.to_s.humanize

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Usuario creado exitosamente.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'Datos de usuario actualizados.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
	def resource_name
    	:user
  	end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h2>Edit <%= resource_name.to_s.humanize %></h2>

<%= simple_form_for(resource, :as => resource_name, :url => edit_user_path(resource_name), :html => { :method => :put }) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :email, :required => true, :autofocus => true %>
    <%= f.input :password, :autocomplete => "off", :hint => "leave it blank if you don't want to change it", :required => false %>
    <%= f.input :password_confirmation, :required => false %>
    <%= f.input :current_password, :hint => "we need your current password to confirm your changes", :required => true %>
  </div>

  <div class="actions">
    <%= f.button :submit, "Update" %>
  </div>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%= link_to "Cancel my account", edit_user_path(resource_name), :confirm => "Are you sure?", :method => :delete %>.</p>

<%= link_to "Back", :back %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Usuarios</h1>
<%= link_to "Actividad", activities_path, :class => "btn btn-inverse" %>

<div class="well row">
  <% @users.in_groups_of(3, false).each do |row_users| %>
    <div class = "row">
    <% for user in row_users %>
    <div class="well span3">
      <div class='text-center'>
        <%= image_tag user.avatar.url(:thumb) , :class => "img-circle" %><br>
        <%= link_to user.username, user %>
        <p>
          <%= time_ago_in_words user.created_at %> ago
        </p>
        <% if user_signed_in? %>
        <p>
          <% if current_user.following?(user) %>
            <%= link_to "Dejar de seguir", follow_destroy_path(:user_id => user.id) %>
          <% elsif current_user.name == user.name %>
            Este eres tú 
          <% else %>
            <%= link_to "Seguir", follow_create_path(:user_id => user.id)%> 
          <%  end %> | <%= link_to 'Show', user %> | Ver preguntas o respuestas hechas...
        </p>
        <% end %>
      </div>
    </div>
    <% end %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<Legend>Sign up</Legend>

<%= simple_form_for(resource, :as => resource_name, :url => new_user_path(resource_name)) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :email, :required => true, :autofocus => true %>
    <%= f.input :password, :required => true %>
    <%= f.input :password_confirmation, :required => true %>
  </div>

  <div class="actions">
    <%= f.button :submit, "Sign up" %>
  </div>
<% end %>

<%= render "links" %>

app/views/users/show.html.erb
<div class="well row">
	<div class="well span3">
		<div class="text-center">
			<%= image_tag @user.avatar.url(:thumb) , :class => "img-circle" %>
			<h5><%= @user.name+" "+@user.lname %></h5>
			<% if current_user.name == @user.name %>
				<%= link_to 'Editar Perfil', edit_user_registration_path(@user) %><br><br>
			<% end %>
		</div>
		<p>
			<%= link_to "Siguiendo: "+@user.follow_count.to_s, follow_show_path(:user_id => @user, :type => 'Siguiendo') %>
		</p>
		<p>
			<%= link_to "Seguidores: "+@user.followers_count.to_s, follow_show_path(:user_id => @user, :type => 'Seguidores')%>
		</p>
		<p>
			<%= link_to "Actividad", activities_show_path(:user_id => @user)%>
		</p>
		<p>
			Reputación:  
		</p>
		<p>
			Favoritos:  
		</p>
		<p>
			Mejores Respuestas:  
		</p>
		<p>
			Antiguedad:  
		    <%= time_ago_in_words @user.created_at %>
		</p>
	</div>
	<div class="span7 text-center">
	<p class="text-center">
		<h2 class="text-center">Preguntas realizadas</h2>
	</p>

	<% current_user.questions.each do |question| %>
  		<h3> <%= link_to question.title, question %></h3>
		  Hace <%= time_ago_in_words question.created_at %>
		  por <%= link_to question.user.username, question.user %>
		  <p>
		  <%= link_to 'Detalles', question %> |
		  <%= pluralize(question.qcomments.count, 'Comentario' , 'Comentarios' )%> |
		  <%= pluralize(question.answers.count, 'Respuesta', 'Respuestas')%>
		  </p>
	<% end -%>
	</div>
</div>