config/routes.rb
Users::Application.routes.draw do

  get "vote/add"

  get "vote/remove"

  get "acomments/create"

  get "acomments/destroy"

  get "answers/create"

  get "answers/edit"

  get "answers/destroy"

  get "qcomments/create"

  get "qcomments/destroy"

  post "questions/mejor_respuesta"

  resources :questions do
    resources :qcomments, :answers, :acomments
  end

  get "message/show"

  get "message/destroy"

  get "follow/create"
  get "follow/destroy"
  get "follow/show"

  root :to => 'questions#index'

  devise_for :users

  ActiveAdmin.routes(self)

  resources :activities
  get "activities/show"

  resources :users

  match 'users/:id/edit' => 'devise/registrations#edit'

end

app/models/acomment.rb
class Acomment < ActiveRecord::Base
	belongs_to :answer
	belongs_to :user
	belongs_to :question
  attr_accessible :answer_id, :text, :user_id, :question_id
  

  validates_presence_of :text
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_many :acomments, 	:dependent => :delete_all
  has_many :votes, 		:dependent => :delete_all
  attr_accessible :question_id, :text, :user_id, :votos
  

  validates_presence_of :text
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  include PublicActivity::Common
  #tracked owner: ->(controller, model) { controller.current_user }  

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/qcomment.rb
class Qcomment < ActiveRecord::Base
	belongs_to :question
	belongs_to :user
  attr_accessible :question_id, :text, :user_id
  

  validates_presence_of :text
end

app/models/question.rb
class Question < ActiveRecord::Base
  include PublicActivity::Common
  
  belongs_to :user
  has_many :qcomments, 	:dependent => :delete_all
  has_many :answers, 	:dependent => :delete_all
  has_many :acomments, 	:dependent => :delete_all
  accepts_nested_attributes_for :answers
  attr_accessible :title, :text, :user_id, :mejor_respuesta
  

  validates_presence_of :title
end

app/models/user.rb
class User < ActiveRecord::Base
  include PublicActivity::Common
  
  devise :database_authenticatable, :recoverable, 
         :rememberable, :trackable, :validatable, :registerable 
  	
  attr_accessible :login, :name, :lname, :username, :email, :password, :password_confirmation, 
                  :remember_me, :avatar

  has_many :questions,  :dependent => :delete_all
  has_many :qcomments,  :dependent => :delete_all
  has_many :answers,    :dependent => :delete_all
  has_many :acomments,  :dependent => :delete_all
  has_many :votes,      :dependent => :delete_all

  validates_uniqueness_of :username
  validates_presence_of :username
  validates_presence_of :name
  validates_presence_of :lname

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/user-avatar.png"

    # Virtual attribute for authenticating by either username or email
	# This is in addition to a real persisted field like 'username'
	attr_accessor :login

  acts_as_followable

  acts_as_follower

  acts_as_messageable

	# app/models/user.rb

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

	### This is the correct method you override with the code above
	### def self.find_for_database_authentication(warden_conditions)
	### end 

  extend FriendlyId
  friendly_id :username
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :user
	belongs_to :answer
  attr_accessible :answer_id, :user_id
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/vote_controller.rb
class VoteController < ApplicationController
  def add
  	@question = Question.find(params[:Qid])
  	@answer = Answer.find(params[:Aid])
  	@voto = Vote.where(:answer_id => @answer.id , :user_id => current_user.id)
    if @voto.empty?

    	@vote = Vote.new
    	@vote.answer_id = @answer.id
    	@vote.user_id = current_user.id
    	@vote.save

  		@answer.votos += 1
  		@answer.save

      @user = User.find(@answer.user_id)
      current_user.send_message(@user, "Up" , @question.id)
    	flash[:notice] = "Voto guardado"
  	else
    	flash[:alert] = "No puedes votar dos veces en la misma respuesta."
  	end
  	redirect_to @question
  end

  def remove
  	@question = Question.find(params[:Qid])
  	@answer = Answer.find(params[:Aid])
  	
  	@voto = Vote.where(:answer_id => @answer.id , :user_id => current_user.id)
    if @voto.empty?

    	@vote = Vote.new
    	@vote.answer_id = @answer.id
    	@vote.user_id = current_user.id
    	@vote.save

  		@answer.votos -= 1
  		@answer.save

      @user = User.find(@answer.user_id)
      current_user.send_message(@user, "Down" , @question.id)
    	flash[:notice] = "Voto guardado"
  	else
    	flash[:alert] = "No puedes votar dos veces en la misma pregunta."
  	end
  	redirect_to @question
  end
end

app/helpers/acomments_helper.rb
module AcommentsHelper
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/follow_helper.rb
module FollowHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/qcomments_helper.rb
module QcommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def resource_name
    	:user
  	end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/vote_helper.rb
module VoteHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container"><!-- Collapsable nav bar -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <!-- Your site name for the upper left corner of the site -->
      <%= link_to "HazTuPregunta", root_path, {:class => 'brand'}, { :title => "Inicio" } %>
      
      <div class="nav-collapse"><!-- Other nav bar content -->
        <ul class="nav">
          <li>
            <%= link_to "Usuarios", users_path, { :title => "Ver Usuarios" } %>
          </li>
        </ul>
      </div>

      <!-- Start of the nav bar content -->
      <div class="nav-collapse"><!-- Other nav bar content -->

      <!-- The drop down menu -->
      <ul class="nav pull-right">
        <% if user_signed_in? %>
          <li>
          <%= link_to raw(current_user.name+' <i class="icon-user"></i>'), user_path(current_user), { :title => "Ver mi Perfil" }  %>
          </li>
          <li>
          <%= link_to raw(current_user.received_messages.unreaded.count.to_s+' <i class="icon-comment"></i>'), message_show_path(:user_id => current_user), { :title => "Notificaciones" }  %>
          </li>
        <% else %>
          <li>
          <%= link_to(raw('Registrarse <i class="icon-edit"></i>'), new_user_registration_path)  %>
          </li>
        <% end %>
        <li class="divider-vertical"></li>

        <% if user_signed_in? %>
          <li>
          <%= link_to raw('Cerrar Sesión <i class="icon-off"></i>'), destroy_user_session_path, :method=>'delete'%>
          </li>
        <% else %>
          <li class="drop down">
            <a class="dropdown-toggle" href="#" data-toggle="dropdown">Iniciar Sesión <i class="icon-chevron-down"></i></a>
            <div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
            <!-- Login form here -->
            <%= simple_form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
              <%= f.input :login, :label => 'Nombre de Usuario o Correo', :required => false, :autofocus => true, :placeholder => 'login' %>
              <%= f.input :password, :required => false, :placeholder => 'contraseña', :label => 'Contraseña' %>
              <label class="checkbox">
                <%= f.input :remember_me, :label => 'Recordar Datos', :as => :boolean if devise_mapping.rememberable? %>
              </label>
              <%= f.button :submit, "Iniciar Sesión" %>
              <% end %>
              <%= render "devise/links" %><br>
            </div>
          </li>
        <% end %>
      </ul>
      </div>
    </div>
  </div>
</div>

<script>
$('.dropdown-menu input, .dropdown-menu label').click(function(e) {
    e.stopPropagation();
});
</script>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "HazTuPregunta" %></title>
    <link rel="shortcut icon" href="/images/favicon.png"/>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header><br><br>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= link_to "Hacer una pregunta", new_question_path , :class => "btn btn-inverse" %><br><br>
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>